version: '3.4'
services:
  db:
    container_name: har_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - 5432:5432
    volumes:
      - ./db/lib/postgresql:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    container_name: har_rabbitmq
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbit:/var/lib/rabbitmq/mnesia
      - ./conf/:/etc/rabbitmq/
  backend:
    container_name: har_backend
    image: instahipsta/har_service:0.10
    restart: always
    ports:
    - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:8080/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 90s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      - db
      - rabbitmq