version: '3.1'
services:
  db:
    container_name: har_service_db
    image: postgres
    restart: always
    env_file:
      - postgresql.env
    ports:
      - 5432:5432
    volumes:
      - ./db/lib/postgresql:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    container_name: har_rabbitmq
    image: rabbitmq:3-management
    restart: always
    env_file:
      - rabbitmq.env
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbit:/var/lib/rabbitmq/mnesia
      - ./conf/:/etc/rabbitmq/