spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/har_service
    password: root
    username: root
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  rabbitmq:
    host: 127.0.0.1
    username: root
    password: root
file:
  downloads: ./downloads

---

spring:
  profiles: test
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/har_service_test
    password: root
    username: root
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  rabbitmq:
    host: 127.0.0.1
    username: root
    password: root
file:
  downloads: test_downloads
