spring:
  profiles:
    active: dev

---

spring:
  profiles: prod
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/har_service
    password: root
    username: root
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  rabbitmq:
    host: rabbitmq
    username: root
    password: root
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
          stateless: true

  liquibase:
    enabled: true
    change-log: classpath*:db.changelog/changelog.yml

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

rabbitmq:
  harQueue: harQueue
  deadletterQueue: deadletterQueue
  harExchange: harExchange
  deadletterExchange: dead-letter-exchange
  harRoutingKey: har
  deadletterRoutingKey: deadletterRoutingKey

---

spring:
  profiles: dev
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/har_service
    password: root
    username: root
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  rabbitmq:
    host: 127.0.0.1
    username: root
    password: root
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
          stateless: true

  liquibase:
    enabled: false
    change-log: classpath*:db.changelog/changelog.yml

rabbitmq:
  harQueue: harQueue
  deadletterQueue: deadletterQueue
  harExchange: harExchange
  deadletterExchange: dead-letter-exchange
  harRoutingKey: har
  deadletterRoutingKey: deadletterRoutingKey
