spring:
  profiles:
    active: dev

---

spring:
  profiles: prod
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/har_service
    password: root
    username: root
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  rabbitmq:
    host: rabbitmq
    username: root
    password: root
  liquibase:
    enabled: true
    change-log: classpath*:db.changelog/db.changelog-master-dev.yaml

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

file:
  downloads: ./downloads

---

spring:
  profiles: dev
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/har_service
    password: root
    username: root
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  rabbitmq:
    host: 127.0.0.1
    username: root
    password: root
  liquibase:
    enabled: true
    change-log: classpath*:db.changelog/db.changelog-master-dev.yaml

file:
  downloads: ./downloads

---

spring:
  profiles: test
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/har_service_test
    password: root
    username: root
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  rabbitmq:
    host: 127.0.0.1
    username: root
    password: root
  liquibase:
    enabled: true
    change-log: classpath*:db.changelog/db.changelog-master-dev.yaml
file:
  downloads: test_downloads
  filesForTests: filesForTests
